/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: w02_dds_types.h
  Source: /home/zwc/cpp_ipc_dds/test/w02_dds_types.idl
  Cyclone DDS: V0.10.2

*****************************************************************/
#ifndef DDSC_W02_DDS_TYPES_H
#define DDSC_W02_DDS_TYPES_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_DOUBLE_DEFINED
#define DDS_SEQUENCE_DOUBLE_DEFINED
typedef struct dds_sequence_double
{
  uint32_t _maximum;
  uint32_t _length;
  double *_buffer;
  bool _release;
} dds_sequence_double;

#define dds_sequence_double__alloc() \
((dds_sequence_double*) dds_alloc (sizeof (dds_sequence_double)));

#define dds_sequence_double_allocbuf(l) \
((double *) dds_alloc ((l) * sizeof (double)))
#endif /* DDS_SEQUENCE_DOUBLE_DEFINED */

#ifndef DDS_SEQUENCE_LONG_DEFINED
#define DDS_SEQUENCE_LONG_DEFINED
typedef struct dds_sequence_long
{
  uint32_t _maximum;
  uint32_t _length;
  int32_t *_buffer;
  bool _release;
} dds_sequence_long;

#define dds_sequence_long__alloc() \
((dds_sequence_long*) dds_alloc (sizeof (dds_sequence_long)));

#define dds_sequence_long_allocbuf(l) \
((int32_t *) dds_alloc ((l) * sizeof (int32_t)))
#endif /* DDS_SEQUENCE_LONG_DEFINED */

#ifndef DDS_SEQUENCE_STRING_DEFINED
#define DDS_SEQUENCE_STRING_DEFINED
typedef struct dds_sequence_string
{
  uint32_t _maximum;
  uint32_t _length;
  char **_buffer;
  bool _release;
} dds_sequence_string;

#define dds_sequence_string__alloc() \
((dds_sequence_string*) dds_alloc (sizeof (dds_sequence_string)));

#define dds_sequence_string_allocbuf(l) \
((char **) dds_alloc ((l) * sizeof (char*)))
#endif /* DDS_SEQUENCE_STRING_DEFINED */

typedef struct w02_Sample
{
  int64_t seq;
  int32_t idx_flags;
  int64_t produced_ns;
  int64_t enter_ns;
  int32_t hdr_xor;
  int64_t prev_seq;
  int64_t prev_done_ns;
  dds_sequence_double data1;
  dds_sequence_long data2;
  dds_sequence_string data3;
  bool data4;
} w02_Sample;

extern const dds_topic_descriptor_t w02_Sample_desc;

#define w02_Sample__alloc() \
((w02_Sample*) dds_alloc (sizeof (w02_Sample)));

#define w02_Sample_free(d,o) \
dds_sample_free ((d), &w02_Sample_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_W02_DDS_TYPES_H */
